config/routes.rb
Rails.application.routes.draw do

  resources :includeds do
    member do
      put 'include', to: 'includeds#include'
      put 'exclude', to: 'includeds#exclude'
      get 'csv', to: 'includeds#csv'
    end
  end

  resources :springers do
    member do
      put 'select', to: 'springers#select'
      put 'unselect', to: 'springers#unselect'
    end
  end
  resources :scopus do
    member do
      put 'select', to: 'scopus#select'
      put 'unselect', to: 'scopus#unselect'
    end
  end
  resources :scidirs do
    member do
      put 'select', to: 'scidirs#select'
      put 'unselect', to: 'scidirs#unselect'
    end
  end
  resources :acms do
    member do
      put 'select', to: 'acms#select'
      put 'unselect', to: 'acms#unselect'
    end
  end
  resources :ieees do
    member do
      put 'select', to: 'ieees#select'
      put 'unselect', to: 'ieees#unselect'
    end
  end

  resources :springers_users_protocols do
    member do
      put 'select', to: 'springers_users_protocols#select'
      put 'unselect', to: 'springers_users_protocols#unselect'
      put 'include', to: 'springers_users_protocols#include'
      put 'exclude', to: 'springers_users_protocols#exclude'
      put 'maybe', to: 'springers_users_protocols#maybe'
      get 'csv', to: 'springers_users_protocols#csv'
    end
  end
  resources :scopus_users_protocols do
    member do
      put 'select', to: 'scopus_users_protocols#select'
      put 'unselect', to: 'scopus_users_protocols#unselect'
      put 'include', to: 'scopus_users_protocols#include'
      put 'exclude', to: 'scopus_users_protocols#exclude'
      put 'maybe', to: 'scopus_users_protocols#maybe'
      get 'csv', to: 'scopus_users_protocols#csv'
    end
  end
  resources :scidirs_users_protocols do
    member do
      put 'select', to: 'scidirs_users_protocols#select'
      put 'unselect', to: 'scidirs_users_protocols#unselect'
      put 'include', to: 'scidirs_users_protocols#include'
      put 'exclude', to: 'scidirs_users_protocols#exclude'
      put 'maybe', to: 'scidirs_users_protocols#maybe'
      get 'csv', to: 'scidirs_users_protocols#csv'
    end
  end
  resources :acms_users_protocols do
    member do
      put 'select', to: 'acms_users_protocols#select'
      put 'unselect', to: 'acms_users_protocols#unselect'
      put 'include', to: 'acms_users_protocols#include'
      put 'exclude', to: 'acms_users_protocols#exclude'
      put 'maybe', to: 'acms_users_protocols#maybe'
      get 'csv', to: 'acms_users_protocols#csv'
    end
  end
  resources :ieees_users_protocols do
    member do
      put 'select', to: 'ieees_users_protocols#select'
      put 'unselect', to: 'ieees_users_protocols#unselect'
      put 'include', to: 'ieees_users_protocols#include'
      put 'exclude', to: 'ieees_users_protocols#exclude'
      put 'maybe', to: 'ieees_users_protocols#maybe'
      get 'csv', to: 'ieees_users_protocols#csv'
    end
  end

  resources :users_protocols do
    member do
      put 'submit'
      get 'show_conflicts'
      get 'included'
    end
  end

  resources :references do
    collection do
      post 'distribute'
    end
  end

  resources :protocols do
    member do
      get 'search'
      post 'do_search'
      get 'selected'
      get 'included'
      get 'distribute_studies', to: 'references#distribute_studies'
    end
  end

  get 'terms_of_service', to: 'home#terms_of_service'
  get 'privacy_policy', to: 'home#privacy_policy'
  get 'community_rules', to: 'home#community_rules'
  get 'user_manual', to: 'home#user_manual'

  devise_for :users

  root 'protocols#index'

end

app/models/reference.rb
class Reference < ActiveRecord::Base

  belongs_to :protocol

end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  before_action only: [:show, :edit, :update, :destroy]

  # GET /references
  # GET /references.json
  def index
    @references = Reference.all
  end

  # GET /references/1
  # GET /references/1.json
  def show
    @users_protocols_range = Protocol.find(params[:id]).users_protocols.includes(:user).each do |user_protocol|
      puts user_protocol.id
      puts user_protocol.role.name
      puts user_protocol.user.username
    end

    @reference = Reference.where('protocol_id = ?', params[:id])
    user_protocol = UsersProtocol.where('protocol_id = ? and user_id = ?', params[:id], current_user.id).select('id').first
    ieees = Ieee.where('protocol_id = ?', params[:id]).select('id')
    acms = Acm.where('protocol_id = ?', params[:id]).select('id')
    scopus = Scopu.where('protocol_id = ?', params[:id]).select('id')
    springers = Springer.where('protocol_id = ?', params[:id]).select('id')
    scidirs = Scidir.where('protocol_id = ?', params[:id]).select('id')
    @ieee = IeeesUsersProtocol.where('ieee_id in (?) AND users_protocol_id = ? AND pre_selected IS NULL', ieees, user_protocol.id)
    @acm = AcmsUsersProtocol.where('acm_id in (?) AND users_protocol_id = ? AND pre_selected IS NULL', acms, user_protocol.id)
    @scopus = ScopusUsersProtocol.where('scopu_id in (?) AND users_protocol_id = ? AND pre_selected IS NULL', scopus, user_protocol.id)
    @springer = SpringersUsersProtocol.where('springer_id in (?) AND users_protocol_id = ? AND pre_selected IS NULL', springers, user_protocol.id)
    @scidir = ScidirsUsersProtocol.where('scidir_id in (?) AND users_protocol_id = ? AND pre_selected IS NULL', scidirs, user_protocol.id)
  end

  # GET /references/new
  def new
    @reference = Reference.new
  end

  # GET /references/1/edit
  def edit
  end

  def distribute_studies
    @users_protocols_range = Protocol.find(params[:id]).users_protocols.includes(:user).each do |user_protocol|
      puts user_protocol.id
      puts user_protocol.role.name
      puts user_protocol.user.username
    end
    respond_to do |format|
      format.html { render :partial => 'distribute_studies' }
      format.js {  }
    end
  end

  def distribute
    hash = Hash.new()

    params[:distribution].each do | user_range |
      userProtocolId = user_range[:user_id].to_i
      range = user_range[:range].to_i
      hash[userProtocolId] = range
      @user_protocol = UsersProtocol.find(userProtocolId)
      if @protocol.nil?
        @protocol = @user_protocol.protocol
      end
      @user_protocol.selection_submitted = false
      @user_protocol.save!
    end

    if !hash.empty?
      Included.where(protocol_id: @protocol.id).delete_all

      IeeesUsersProtocol.randomize_studies(hash, @protocol) if @protocol.ieee?

      ScidirsUsersProtocol.randomize_studies(hash, @protocol) if @protocol.science_direct?

      AcmsUsersProtocol.randomize_studies(hash, @protocol) if @protocol.acm?

      SpringersUsersProtocol.randomize_studies(hash, @protocol) if @protocol.springer?

      ScopusUsersProtocol.randomize_studies(hash, @protocol) if @protocol.scopus?
    end

    Included.destroy_all(protocol_id: @protocol.id)

    redirect_to :back
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_reference
    @reference = Reference.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def reference_params
    params.require(:reference).permit(:query)
  end

end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/views/references/_distribute_studies.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3 id="modalLabel">Distribuir Estudos</h3>
</div>
<div class="modal-body">
  <table class="table table-bordered" id="modal_table">
    <thead>
    <tr>
      <th>Integrante</th>
      <th>Papel</th>
      <th>Distribuição</th>
    </tr>
    </thead>
    <tbody>
    <% @users_protocols_range.each do |user_protocol| %>
        <tr>
          <td hidden><%= user_protocol.id %></td>
          <td><%= user_protocol.user.username %></td>
          <td><%= user_protocol.role.name %></td>
          <td>
            &nbsp;
            <span class="range-content">
                <input type="range" data-slider-min="0" data-slider-max="100" data-slider-step="1" data-slider-value="100"/>
                &nbsp;&nbsp;<span>100</span>
              </span>
            <span>%</span>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>
<div class="modal-footer">
  <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
  <button id="btnDistribute" class="btn btn-primary">Distribuir</button>
</div>

app/views/references/_form.html.erb
<%= form_for(@reference) do |f| %>
  <% if @reference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reference.errors.count, "error") %> prohibited this reference from being saved:</h2>

      <ul>
      <% @reference.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :query %><br>
    <%= f.text_field :query %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/references/edit.html.erb
<h1>Editing Reference</h1>

<%= render 'form' %>

<%= link_to 'Show', @reference %> |
<%= link_to 'Back', references_path %>

app/views/references/new.html.erb
<h1>New Reference</h1>

<%= render 'form' %>

<%= link_to 'Back', references_path %>

app/views/references/show.html.erb
<br>

<ol class="breadcrumb">
  <li><%= link_to 'Protocolo', protocol_path %></li>
  <li><%= link_to 'Execução da Busca', search_protocol_path %></li>
  <li class="active"> Resultados Retornados </li>
  <li><%= link_to 'Trabalhos pré-selecionados', selected_protocol_path %></li>
</ol>

<div class="container-fluid">
  <div class="table">
    <table class="table table-hover">
      <tr>
        <th> Base Digital </th>
        <th> Resultado Total </th>
        <th> Resultados a serem analisados </th>
        <th> Resultados atribuídos </th>
        <th> Data </th>
      </tr>
      <tr>
        <% Reference.all.each do |reference| %>
            <% if reference.protocol_id == params[:id] %>
              <% if reference.database == 'scopu' %>
                  <tr>
                    <td>
                      <% if reference.total_found == 0 %>
                        <%= reference.database_name %>
                      <% else %>
                        <%= link_to reference.database_name, scopus_users_protocol_path %>
                      <% end %>
                    </td>
                    <td align="center">
                      <%= reference.total_found %>
                    </td>
                    <td align="center">
                      <%= reference.results %>
                    </td>
                    <td align="center">
                      <%= @scopus.count %>
                    </td>
                    <td>
                      <%= (reference.updated_at.to_s[0..10])%>
                    </td>
                  </tr>
              <% end %>
              <% if reference.database == 'ieee' %>
                  <tr>
                    <td>
                      <% if reference.total_found == 0 || @ieee.count == 0 %>
                          <%= reference.database_name %>
                      <% else %>
                          <%= link_to reference.database_name, ieees_users_protocol_path %>
                      <% end %>
                    </td>
                    <td align="center">
                      <%= reference.total_found %>
                    </td>
                    <td align="center">
                      <%= reference.results %>
                    </td>
                    <td align="center">
                    <%= @ieee.count %>
                  </td>
                    <td>
                      <%= (reference.updated_at.to_s[0..10])%>
                    </td>
                  </tr>
              <% end %>
              <% if reference.database == 'scidir' %>
                  <tr>
                    <td>
                      <% if reference.total_found == 0 || @scidir.count == 0  %>
                          <%= reference.database_name %>
                      <% else %>
                          <%= link_to reference.database_name, scidirs_users_protocol_path %>
                      <% end %>
                    </td>
                    <td align="center">
                      <%= reference.total_found %>
                    </td>
                    <td align="center">
                      <%= reference.results %>
                    </td>
                    <td align="center">
                      <%= @scidir.count %>
                    </td>
                    <td>
                      <%= (reference.updated_at.to_s[0..10])%>
                    </td>
                  </tr>
              <% end %>
              <% if reference.database == 'acm' %>
                  <tr>
                    <td>
                      <% if reference.total_found == 0 || @acm.count == 0  %>
                          <%= reference.database_name %>
                      <% else %>
                          <%= link_to reference.database_name, acms_users_protocol_path %>
                      <% end %>
                    </td>
                    <td align="center">
                      <%= reference.total_found %>
                    </td>
                    <td align="center">
                      <%= reference.results %>
                    </td>
                    <td align="center">
                      <%= @acm.count %>
                    </td>
                    <td>
                      <%= (reference.updated_at.to_s[0..10])%>
                    </td>
                  </tr>
              <% end %>
              <% if reference.database == 'springer' %>
                  <tr>
                    <td>
                      <% if reference.total_found == 0 || @springer.count == 0  %>
                          <%= reference.database_name %>
                      <% else %>
                          <%= link_to reference.database_name, springers_users_protocol_path %>
                      <% end %>
                    </td>
                    <td align="center">
                      <%= reference.total_found %>
                    </td>
                    <td align="center">
                      <%= reference.results %>
                    </td>
                    <td align="center">
                      <%= @springer.count %>
                    </td>
                    <td>
                      <%= (reference.updated_at.to_s[0..10])%>
                    </td>
                  </tr>
              <% end %>
            <% end %>
        <% end %>
      </tr>
    </table>
  </div>
</div>

  <%= link_to 'Distribuir',
              distribute_studies_protocol_path,
              {
                :remote => true,
                'data-toggle' =>  'modal',
                'data-target' => '#distribute_studies',
                :class => 'btn btn-primary ', 'data-type' => 'html'
              }
  %>
<!-- Modal -->
<div class="modal fade" id="distribute_studies">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= render partial: 'distribute_studies' %>
    </div>
  </div>
</div>
<!-- End of Modal -->
</div>