config/routes.rb
Rails.application.routes.draw do

  resources :includeds do
    member do
      put 'include', to: 'includeds#include'
      put 'exclude', to: 'includeds#exclude'
      get 'csv', to: 'includeds#csv'
    end
  end

  resources :springers do
    member do
      put 'select', to: 'springers#select'
      put 'unselect', to: 'springers#unselect'
    end
  end
  resources :scopus do
    member do
      put 'select', to: 'scopus#select'
      put 'unselect', to: 'scopus#unselect'
    end
  end
  resources :scidirs do
    member do
      put 'select', to: 'scidirs#select'
      put 'unselect', to: 'scidirs#unselect'
    end
  end
  resources :acms do
    member do
      put 'select', to: 'acms#select'
      put 'unselect', to: 'acms#unselect'
    end
  end
  resources :ieees do
    member do
      put 'select', to: 'ieees#select'
      put 'unselect', to: 'ieees#unselect'
    end
  end

  resources :springers_users_protocols do
    member do
      put 'select', to: 'springers_users_protocols#select'
      put 'unselect', to: 'springers_users_protocols#unselect'
      put 'include', to: 'springers_users_protocols#include'
      put 'exclude', to: 'springers_users_protocols#exclude'
      put 'maybe', to: 'springers_users_protocols#maybe'
      get 'csv', to: 'springers_users_protocols#csv'
    end
  end
  resources :scopus_users_protocols do
    member do
      put 'select', to: 'scopus_users_protocols#select'
      put 'unselect', to: 'scopus_users_protocols#unselect'
      put 'include', to: 'scopus_users_protocols#include'
      put 'exclude', to: 'scopus_users_protocols#exclude'
      put 'maybe', to: 'scopus_users_protocols#maybe'
      get 'csv', to: 'scopus_users_protocols#csv'
    end
  end
  resources :scidirs_users_protocols do
    member do
      put 'select', to: 'scidirs_users_protocols#select'
      put 'unselect', to: 'scidirs_users_protocols#unselect'
      put 'include', to: 'scidirs_users_protocols#include'
      put 'exclude', to: 'scidirs_users_protocols#exclude'
      put 'maybe', to: 'scidirs_users_protocols#maybe'
      get 'csv', to: 'scidirs_users_protocols#csv'
    end
  end
  resources :acms_users_protocols do
    member do
      put 'select', to: 'acms_users_protocols#select'
      put 'unselect', to: 'acms_users_protocols#unselect'
      put 'include', to: 'acms_users_protocols#include'
      put 'exclude', to: 'acms_users_protocols#exclude'
      put 'maybe', to: 'acms_users_protocols#maybe'
      get 'csv', to: 'acms_users_protocols#csv'
    end
  end
  resources :ieees_users_protocols do
    member do
      put 'select', to: 'ieees_users_protocols#select'
      put 'unselect', to: 'ieees_users_protocols#unselect'
      put 'include', to: 'ieees_users_protocols#include'
      put 'exclude', to: 'ieees_users_protocols#exclude'
      put 'maybe', to: 'ieees_users_protocols#maybe'
      get 'csv', to: 'ieees_users_protocols#csv'
    end
  end

  resources :users_protocols do
    member do
      put 'submit'
      get 'show_conflicts'
      get 'included'
    end
  end

  resources :references do
    collection do
      post 'distribute'
    end
  end

  resources :protocols do
    member do
      get 'search'
      post 'do_search'
      get 'selected'
      get 'included'
      get 'distribute_studies', to: 'references#distribute_studies'
    end
  end

  get 'terms_of_service', to: 'home#terms_of_service'
  get 'privacy_policy', to: 'home#privacy_policy'
  get 'community_rules', to: 'home#community_rules'
  get 'user_manual', to: 'home#user_manual'

  devise_for :users

  root 'protocols#index'

end

app/models/ieees_users_protocol.rb
class IeeesUsersProtocol < ActiveRecord::Base

  # user_hash = {user_protocol_id, percentage}
  def self.randomize_studies(user_hash, protocol)
    studies = Ieee.where('protocol_id = ?', protocol.id)
    IeeesUsersProtocol.where(ieee_id: studies).delete_all
    total = studies.count()

    # change the percentage to an actual quantity of studies
    user_quantity = {}
    user_hash.each do |key, value|
      user_quantity[key] = (value*total*0.01).to_i
    end

    user_array = user_quantity.to_a

    study_index = 0
    user_index = 0
    stopped = 0
    while stopped != user_array.count
      user_index = user_index.modulo(user_array.count)

      if !user_array[user_index][0].nil?
        if user_array[user_index][1].zero?
          user_array[user_index][0] = nil
          stopped += 1
        else
          user_array[user_index][1] -= 1
          study_index = study_index.modulo(studies.count)
          while IeeesUsersProtocol.exists?(:users_protocol_id => user_array[user_index][0], :ieee_id => studies[study_index].id)
            study_index += 1
            study_index = study_index.modulo(studies.count)
          end
          IeeesUsersProtocol.create(:users_protocol_id => user_array[user_index][0], :ieee_id => studies[study_index].id)
          study_index += 1
        end
      end
      user_index += 1
    end
  end

end

app/controllers/ieees_users_protocols_controller.rb
class IeeesUsersProtocolsController < ApplicationController
  before_action :set_session, only: [:show]
  before_action :set_user_protocol, only: [:show, :select, :unselect, :include, :exclude, :maybe]

  def show
    studies = Ieee.where(protocol_id: params[:id])
    ieees_id = IeeesUsersProtocol.where(users_protocol_id: @user_protocol, pre_selected: nil).select('ieee_id')
    @ieees = studies.where(id: ieees_id).paginate(:page => params[:page], per_page: 10)

    @reference = Reference.find_by_protocol_id(params[:id])
  end

  def select
    @ieee = IeeesUsersProtocol.where(ieee_id: params[:id], users_protocol_id: @user_protocol).first
    @ieee.pre_selected = 1
    @ieee.save!

    redirect_to :back
  end

  def unselect
    @ieee = IeeesUsersProtocol.where(ieee_id: params[:id].to_i, users_protocol_id: @user_protocol).first
    @ieee.pre_selected = 0
    @ieee.save!

    redirect_to :back
  end

  def include
    @ieee = IeeesUsersProtocol.where(ieee_id: params[:id], users_protocol_id: @user_protocol).first
    @ieee.included = 1
    @ieee.save!

    redirect_to :back
  end

  def exclude
    @ieee = IeeesUsersProtocol.where(ieee_id: params[:id].to_i, users_protocol_id: @user_protocol).first
    @ieee.included = 0
    @ieee.save!

    redirect_to :back
  end

  def maybe
    @ieee = IeeesUsersProtocol.where(ieee_id: params[:id], users_protocol_id: @user_protocol).first
    @ieee.maybe = 1
    @ieee.save!

    redirect_to :back
  end

  private
  def set_user_protocol
    @user_protocol = UsersProtocol.where(protocol_id: session[:protocol_id], user_id: current_user.id).first
  end
  def set_session
    session[:protocol_id] = params[:id].to_i
  end
end

app/views/ieees_users_protocols/index.html.erb
<br>

<div class="btn-group">
  <%= link_to 'Continuar', protocol_path(2), class: "btn btn-default" %>
</div>

<br>

<% @ieees.each do |ieee| %>
    <br>
    <div class="panel panel-default">
      <div class="panel-heading"> <b><%= link_to ieee.title, ieee.link  %> </b>
        <%= link_to include_ieee_path(ieee), method: :put, class: 'btn btn-default btn-sm' do %>
         <span class="glyphicon glyphicon-chevron-up"></span>
            Incluir
        <% end %>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-12" align="left">
            <h5>
              <b> Autor: </b> <%= ieee.author %> <br>
              <b> Periódico/Conferência: </b> <%= ieee.pubtitle  %><br>
              <b> Abstract: </b> <p> <%= ieee.abstract %> </p>
            </h5>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/ieees_users_protocols/show.html.erb
<br>

<ol class="breadcrumb">
  <li><%= link_to 'Protocolo', protocol_path %></li>
  <li><%= link_to 'Execução da Busca', search_protocol_path %></li>
  <li><%= link_to 'Resultados Retornados', reference_path %></li>
  <li class="active"> IEEE Xplore Digital Library </li>
  <li><%= link_to 'Trabalhos pré-selecionados', selected_protocol_path %></li>
</ol>

<% if @reference.results == 0 %>
    <div class="alert alert-info"><b> Nenhum trabalho retornado! </b></div>
<% else %>
    <% if @ieees.empty? %>
        <div class="alert alert-info"><b> Todos trabalhos desta base já foram revisados! </b></div>
    <% else %>
        <% @ieees.each do |ieee| %>
            <br>
            <div class="panel panel-default">
              <div class="panel-heading" align="left"> <b><%= link_to ieee.title, ieee.link  %> </b>
                <div align="right">
                  <%= link_to select_ieees_users_protocol_path(ieee), method: :put, class: 'btn btn-default btn-sm' do %>
                      <span class="glyphicon glyphicon-ok"></span>
                      Incluir
                  <% end %>
                  <%= link_to unselect_ieees_users_protocol_path(ieee), method: :put, class: 'btn btn-default btn-sm' do %>
                      <span class="glyphicon glyphicon-remove"></span>
                      Excluir
                  <% end %>
                </div>
              </div>
              <div class="panel-body">
                <div class="row">
                  <div class="col-lg-12" align="left">
                    <h5>
                      <b> Autores: </b> <%= ieee.author %> <br>
                      <b> Periódico/Conferência: </b> <%= ieee.pubtitle  %><br>
                      <b> Ano: </b> <%= ieee.year  %><br>
                      <b> Abstract: </b> <p class="text-justify"> <%= ieee.abstract %> </p>
                    </h5>
                  </div>
                </div>
              </div>
            </div>
        <% end %>
    <% end %>
<% end %>

<%= will_paginate @ieees, renderer: BootstrapPagination::Rails %>