config/routes.rb
Rails.application.routes.draw do

  resources :includeds do
    member do
      put 'include', to: 'includeds#include'
      put 'exclude', to: 'includeds#exclude'
      get 'csv', to: 'includeds#csv'
    end
  end

  resources :springers do
    member do
      put 'select', to: 'springers#select'
      put 'unselect', to: 'springers#unselect'
    end
  end
  resources :scopus do
    member do
      put 'select', to: 'scopus#select'
      put 'unselect', to: 'scopus#unselect'
    end
  end
  resources :scidirs do
    member do
      put 'select', to: 'scidirs#select'
      put 'unselect', to: 'scidirs#unselect'
    end
  end
  resources :acms do
    member do
      put 'select', to: 'acms#select'
      put 'unselect', to: 'acms#unselect'
    end
  end
  resources :ieees do
    member do
      put 'select', to: 'ieees#select'
      put 'unselect', to: 'ieees#unselect'
    end
  end

  resources :springers_users_protocols do
    member do
      put 'select', to: 'springers_users_protocols#select'
      put 'unselect', to: 'springers_users_protocols#unselect'
      put 'include', to: 'springers_users_protocols#include'
      put 'exclude', to: 'springers_users_protocols#exclude'
      put 'maybe', to: 'springers_users_protocols#maybe'
      get 'csv', to: 'springers_users_protocols#csv'
    end
  end
  resources :scopus_users_protocols do
    member do
      put 'select', to: 'scopus_users_protocols#select'
      put 'unselect', to: 'scopus_users_protocols#unselect'
      put 'include', to: 'scopus_users_protocols#include'
      put 'exclude', to: 'scopus_users_protocols#exclude'
      put 'maybe', to: 'scopus_users_protocols#maybe'
      get 'csv', to: 'scopus_users_protocols#csv'
    end
  end
  resources :scidirs_users_protocols do
    member do
      put 'select', to: 'scidirs_users_protocols#select'
      put 'unselect', to: 'scidirs_users_protocols#unselect'
      put 'include', to: 'scidirs_users_protocols#include'
      put 'exclude', to: 'scidirs_users_protocols#exclude'
      put 'maybe', to: 'scidirs_users_protocols#maybe'
      get 'csv', to: 'scidirs_users_protocols#csv'
    end
  end
  resources :acms_users_protocols do
    member do
      put 'select', to: 'acms_users_protocols#select'
      put 'unselect', to: 'acms_users_protocols#unselect'
      put 'include', to: 'acms_users_protocols#include'
      put 'exclude', to: 'acms_users_protocols#exclude'
      put 'maybe', to: 'acms_users_protocols#maybe'
      get 'csv', to: 'acms_users_protocols#csv'
    end
  end
  resources :ieees_users_protocols do
    member do
      put 'select', to: 'ieees_users_protocols#select'
      put 'unselect', to: 'ieees_users_protocols#unselect'
      put 'include', to: 'ieees_users_protocols#include'
      put 'exclude', to: 'ieees_users_protocols#exclude'
      put 'maybe', to: 'ieees_users_protocols#maybe'
      get 'csv', to: 'ieees_users_protocols#csv'
    end
  end

  resources :users_protocols do
    member do
      put 'submit'
      get 'show_conflicts'
      get 'included'
    end
  end

  resources :references do
    collection do
      post 'distribute'
    end
  end

  resources :protocols do
    member do
      get 'search'
      post 'do_search'
      get 'selected'
      get 'included'
      get 'distribute_studies', to: 'references#distribute_studies'
    end
  end

  get 'terms_of_service', to: 'home#terms_of_service'
  get 'privacy_policy', to: 'home#privacy_policy'
  get 'community_rules', to: 'home#community_rules'
  get 'user_manual', to: 'home#user_manual'

  devise_for :users

  root 'protocols#index'

end

app/models/protocol.rb
class Protocol < ActiveRecord::Base

  has_many :users_protocols, dependent: :destroy
  has_many :users, through: :users_protocols
  has_many :terms, :dependent => :destroy
  has_many :references
  accepts_nested_attributes_for :terms, :allow_destroy => true
  accepts_nested_attributes_for :users_protocols, :allow_destroy => true,
                                reject_if: proc {
                                    |attributes| attributes['user_id'].blank? || attributes['role_id'].blank?
                                }
  validates_presence_of :title, :terms, :from, :to, :users_protocols

  attr_accessor :ref_exists

  def clean_bases (protocol_id)

    # Clean all databases before doing other search

    Ieee.delete_all "protocol_id = #{protocol_id}"
    Scidir.delete_all "protocol_id = #{protocol_id}"
    Scopu.destroy_all "protocol_id = #{protocol_id}"
    Acm.delete_all "protocol_id = #{protocol_id}"
    Springer.delete_all "protocol_id = #{protocol_id}"

    Included.delete_all "protocol_id = #{protocol_id}"

    Reference.delete_all "protocol_id = #{protocol_id}"

  end

  def generate_string(attributes)

    @termos = ''

    attributes.values.each_with_index do |term, index|

      termo = term[:termo].parameterize

      sinonimo = term[:sinonimo] == "" ? '' : '" OR "' + term[:sinonimo].parameterize

      sinonimo2 = term[:sinonimo2] == "" ? '' : '" OR "' + term[:sinonimo2].parameterize

      traducao = term[:traducao] == "" ? '' : '" OR "' + term[:traducao].parameterize

      traducao2 = term[:traducao2] == "" ? '' : '" OR "' + term[:traducao2].parameterize

      traducao3 = term[:traducao3] == "" ? '' : '" OR "' + term[:traducao3].parameterize

      @termos += (index == attributes.size - 1) ?
          '("' + termo + traducao + sinonimo + sinonimo2 + traducao2 + traducao3 + '")' :
          '("' + termo + traducao + sinonimo + sinonimo2 + traducao2 + traducao3 + '")' + ' AND '
    end

    return @termos
  end

end

app/controllers/protocols_controller.rb
class ProtocolsController < ApplicationController
  before_action :set_protocol, only: [:show, :edit, :update, :destroy]

  # GET /protocols
  # GET /protocols.json
  def index
    if !current_user.nil?
      @users_protocols = current_user.users_protocols.includes(:protocol).order(created_at: :desc).each do |user_protocol|
        puts user_protocol.ref_exists = reference_exist_by_id(user_protocol.protocol.id)
      end
    end
  end

  # GET /protocols/1
  # GET /protocols/1.json
  def show
    @role = @protocol.users_protocols.select(:role_id).where(user: current_user).first.role_id
    @users_protocols = @protocol.users_protocols.includes(:user).each do |user_protocol|
      puts user_protocol.role.name
      puts user_protocol.user.username
      puts user_protocol.ref_exists
    end

    session[:protocol_id] = params[:id].to_i
  end

  # GET /protocols/new
  def new
    @protocol = current_user.protocols.build

    1.times { @protocol.terms.build }
    1.times { @protocol.users_protocols.build({ user_id: current_user.id, role_id: 1 }) }

    @protocol.ieee = true
    @protocol.science_direct = true
    @protocol.acm = true
    @protocol.springer = true
    @protocol.from = 2007
    @protocol.to = 2017
  end

  # GET /protocols/1/edit
  def edit
  end

  # POST /protocols
  # POST /protocols.json
  def create
    @protocol = current_user.protocols.build(protocol_params)

    attributes = protocol_params[:terms_attributes]

    @protocol.query = @protocol.generate_string(attributes)

    respond_to do |format|
      if @protocol.save
        format.html { redirect_to @protocol, notice: 'Protocol was successfully created.' }
        format.json { render :show, status: :created, location: @protocol }
      else
        format.html { render :new }
        format.json { render json: @protocol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /protocols/1
  # PATCH/PUT /protocols/1.json
  def update

    attributes = protocol_params[:terms_attributes]

    @protocol.query = @protocol.generate_string(attributes)
    # Como a base Scopus não será mais utilizada, garantir que os
    # protocolos anteriores à atualização não terão mais esta referência
    @protocol.scopus = false
    respond_to do |format|
      if @protocol.update(protocol_params)
        format.html { redirect_to @protocol, notice: 'Protocol was successfully updated.' }
        format.json { render :show, status: :ok, location: @protocol }
      else
        format.html { render :edit }
        format.json { render json: @protocol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /protocols/1
  # DELETE /protocols/1.json
  def destroy
    @protocol.clean_bases(params[:id])

    @protocol.destroy
    respond_to do |format|
      format.html { redirect_to protocols_url, notice: 'Protocol was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @protocol = Protocol.find(params[:id])
    @ref_protocol = reference_exist
  end

  def do_search
    @protocol = Protocol.find(params[:id])

    @protocol.clean_bases(params[:id])

    from = params[:protocol][:from]
    to = params[:protocol][:to]
    query = params[:protocol][:query]
    protocol_id = params[:id]
    max_results = params[:protocol][:results_returned]

    if @protocol.ieee
      @ieee = Ieee.new
      @ieee = @ieee.search(query, protocol_id, max_results, from, to)
    end

    if @protocol.science_direct
      @scidir = Scidir.new
      @scidir = @scidir.search(query, protocol_id, max_results, from, to)
    end

    if @protocol.acm
      @acm = Acm.new
      @acm = @acm.search(query, protocol_id, max_results, from, to)
    end

    if @protocol.springer
      @springer = Springer.new
      @springer = @springer.search(query, protocol_id, max_results, from, to)
    end

    redirect_to reference_url(protocol_id)
  end

  def selected
    @protocol = Protocol.find(params[:id])
    @user_protocol = UsersProtocol.where(protocol_id: params[:id], user_id: current_user.id).first

    @selected_acm = []
    @selected_ieee = []
    @selected_scidir = []
    @selected_springer = []

    if @protocol.ieee
      ieees_id = IeeesUsersProtocol.where(users_protocol_id: @user_protocol, pre_selected: true, maybe: nil, included: nil).select(:ieee_id)
      @selected = Ieee.where(id: ieees_id)

      @selected.each { |ieee|
        @selected_ieee.push(ieee)
      }
    end

    if @protocol.science_direct
      scidirs_id = ScidirsUsersProtocol.where(users_protocol_id: @user_protocol, pre_selected: true, maybe: nil, included: nil).select(:scidir_id)
      @selected = Scidir.where(id: scidirs_id)

      @selected.each { |scidir|
        @selected_scidir.push(scidir)
      }
    end

    if @protocol.acm
      acms_id = AcmsUsersProtocol.where(users_protocol_id: @user_protocol, pre_selected: true, maybe: nil, included: nil).select(:acm_id)
      @selected = Acm.where(id: acms_id)

      @selected.each { |acm|
        @selected_acm.push(acm)
      }
    end

    if @protocol.springer
      springers_id = SpringersUsersProtocol.where(users_protocol_id: @user_protocol, pre_selected: true, maybe: nil, included: nil).select(:springer_id)
      @selected = Springer.where(id: springers_id)

      @selected.each { |springer|
        @selected_springer.push(springer)
      }
    end

    @empty_ieee = (@selected_ieee.empty?) ? true : false
    @empty_scidir = (@selected_scidir.empty?) ? true : false
    @empty_acm = (@selected_acm.empty?) ? true : false
    @empty_springer = (@selected_springer.empty?) ? true : false

    @ref_protocol = reference_exist
  end

  def included
    @protocol = Protocol.find(params[:id])

    @included_ieee = []
    @included_scidir = []
    @included_acm = []
    @included_springer = []

    if @protocol.ieee
      @included = Included.where("protocol_id = ? AND included = 1 AND name_database = 'ieee'", params[:id])

      @included.each { |ieee|
        @included_ieee.push(ieee)
      }

      @count_ieee = @included_ieee.count.to_s
    end

    if @protocol.science_direct
      @included = Included.where("protocol_id = ? AND included = 1 AND name_database = 'scidir'", params[:id])

      @included.each { |scidir|
        @included_scidir.push(scidir)
      }

      @count_scidir = @included_scidir.count.to_s
    end

    if @protocol.acm
      @included = Included.where("protocol_id = ? AND included = 1 AND name_database = 'acm'", params[:id])

      @included.each { |acm|
        @included_acm.push(acm)
      }

      @count_acm = @included_acm.count.to_s
    end

    if @protocol.springer
      @included = Included.where("protocol_id = ? AND included = 1 AND name_database = 'springer'", params[:id])

      @included.each { |springer|
        @included_springer.push(springer)
      }

      @count_springer = @included_springer.count.to_s
    end

    @empty_ieee = (@included_ieee.empty?) ? true : false
    @empty_scidir = (@included_scidir.empty?) ? true : false
    @empty_acm = (@included_acm.empty?) ? true : false
    @empty_springer = (@included_springer.empty?) ? true : false

    @ref_protocol = reference_exist

    @includeds = Included.where("included = 1 AND protocol_id = ?", params[:id])

    respond_to do |format|
      format.html
      format.xls
    end

  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_protocol
    @protocol = Protocol.find(params[:id])
  end


  # Never trust parameters from the scary internet, only allow the white list through.
  def protocol_params
    params.require(:protocol).permit(:id, :title, :background, :research_question, :strategy, :criteria, :from, :to, :results_returned,
                                     :ieee, :acm, :springer, :science_direct, :google_scholar, :scopus, :quality,
                                     :users_protocols_attributes => [:id, :user_id, :role_id, :_destroy],
                                     :terms_attributes => [:id, :termo, :sinonimo, :sinonimo2, :sinonimo3, :traducao, :traducao2, :traducao3, :_destroy])
  end

  # Verifica se alguma busca já foi realizada para aquele protocolo
  def reference_exist
    Reference.find_by_protocol_id(params[:id])
  end
  def reference_exist_by_id(id)
    Reference.find_by_protocol_id(id)
  end
end

app/helpers/protocols_helper.rb
module ProtocolsHelper
end

app/views/protocols/edit.html.erb
<h1>Editar Protocolo</h1>

<%= render 'form' %>

app/views/protocols/included.html.erb
<br>

<ol class="breadcrumb">
  <li><%= link_to 'Protocolo', protocol_path %></li>
  <li><%= link_to 'Execução da Busca', search_protocol_path %></li>
  <li><%= link_to 'Resultados Retornados', reference_path %></li>
  <li><%= link_to 'Trabalhos selecionados', included_users_protocol_path %></li>
  <li><%= link_to 'Resolução de conflitos', show_conflicts_users_protocol_path %></li>
  <li class="active"> Seleção final </li>
</ol>

<% if @empty_ieee && @empty_scidir && @empty_acm && @empty_springer%>
    <div class="alert alert-info"><b> Nenhum trabalho incluído na revisão </b></div>
<% else %>
    <div class="pull-left" >
      <%= link_to included_protocol_path(format: "xls"), class: "btn btn-default" do %>
          Exportar Dados
          <span class="glyphicon glyphicon-download-alt" ></span>
      <% end %>
    </div>
    <br><br>
<% end %>

<% unless @empty_ieee %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <b><%= link_to 'IEEE Xplore Digital Library' + ' (' + @count_ieee + ')', ieee_path  %> </b>
      </div>
      <div class="panel-body">
        <div class="container-fluid">
          <table class="table table-hover">
            <thead>
            <tr>
              <th>Título</th>
              <th>Autores</th>
              <th>Excluir?</th>
            </tr>
            </thead>
            <tbody>
            <% @included_ieee.each do |ref| %>
                <tr>
                  <td><%= link_to ref.title, ref.link %></td>
                  <td><%= ref.author %></td>
                  <td>
                    <%= link_to exclude_included_path(ref), method: :put, class: 'btn btn-default btn-sm' do %>
                        <span class="glyphicon glyphicon-trash"></span>
                    <% end %>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
<% end %>

<% unless @empty_scidir %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <b><%= link_to 'Science Direct Digital Library' + ' (' + @count_scidir + ')', scidir_path %> </b>
      </div>
      <div class="panel-body">
        <div class="container-fluid">
          <table class="table table-hover">
            <thead>
            <tr>
              <th>Título</th>
              <th>Autores</th>
              <th>Excluir?</th>
            </tr>
            </thead>
            <tbody>
            <% @included_scidir.each do |ref| %>
                <tr>
                  <td><%= link_to ref.title, ref.link %></td>
                  <td><%= ref.author %></td>
                  <td>
                    <%= link_to exclude_included_path(ref), method: :put, class: 'btn btn-default btn-sm' do %>
                        <span class="glyphicon glyphicon-trash"></span>
                    <% end %>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
<% end %>

<% unless @empty_acm %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <b><%= link_to 'ACM Digital Library' + ' (' + @count_acm + ')', acm_path %> </b>
      </div>
      <div class="panel-body">
        <div class="container-fluid">
          <table class="table table-hover">
            <thead>
            <tr>
              <th>Título</th>
              <th>Autores</th>
              <th>Excluir?</th>
            </tr>
            </thead>
            <tbody>
            <% @included_acm.each do |ref| %>
                <tr>
                  <td><%= link_to ref.title, ref.link %></td>
                  <td><%= ref.author %></td>
                  <td>
                    <%= link_to exclude_included_path(ref), method: :put, class: 'btn btn-default btn-sm' do %>
                        <span class="glyphicon glyphicon-trash"></span>
                    <% end %>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
<% end %>

<% unless @empty_springer %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <b><%= link_to 'Springer Link Digital Library' + ' (' + @count_springer + ')', springer_path %> </b>
      </div>
      <div class="panel-body">
        <div class="container-fluid">
          <table class="table table-hover">
            <thead>
            <tr>
              <th>Título</th>
              <th>Autores</th>
              <th>Excluir?</th>
            </tr>
            </thead>
            <tbody>
            <% @included_springer.each do |ref| %>
                <tr>
                  <td><%= link_to ref.title, ref.link %></td>
                  <td><%= ref.author %></td>
                  <td>
                    <%= link_to exclude_included_path(ref), method: :put, class: 'btn btn-default btn-sm' do %>
                        <span class="glyphicon glyphicon-trash"></span>
                    <% end %>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
<% end %>

app/views/protocols/new.html.erb
<h1>Novo Protocolo</h1>

<%= render 'form' %>

app/views/protocols/search.html.erb
<br>

<ol class="breadcrumb">
  <li><%= link_to 'Protocolo', protocol_path %></li>
  <li class="active"> Execução da Busca </li>
  <% unless @ref_protocol.nil? %>
      <li><%= link_to 'Resultados Retornados', reference_path %></li>
  <% end %>
</ol>

<%= form_for @protocol, url: do_search_protocol_path, html: {:method => :post}  do |f| %>
    <div class="panel panel-default">
      <div class="panel-heading"><strong> Mecanismo de Busca </strong>  </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-12">
            <div class="form-group" align="left">
              <%= f.label :string_de_busca_genérica %> &nbsp;(Não utilizar acentuação)<br>
              <%= f.text_field :query, class: "form-control" %>
            </div>

            <%= f.hidden_field :id %>
            <%= f.hidden_field :results_returned %>

            <%= f.hidden_field :from %>
            <%= f.hidden_field :to %>


            <%= button_tag( :class => "btn btn-primary btn-lg") do %>
                Buscar <span class="glyphicon glyphicon-search"></span>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading"><strong> String de busca das bases específicas </strong>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-12">
            <table class="table table-bordered">
              <thead>
              <tr>
                <th>Base digital</th>
                <th>String de busca específica</th>
              </tr>
              </thead>
              <tbody>
                <% if @protocol.ieee %>
                  <tr>
                    <td> IEEE Xplore Digital Library </td>
                    <td><%= @protocol.query + '&pys=' + @protocol.from.to_s + '&pye=' + @protocol.to.to_s  %></td>
                  </tr>
                <% end %>

                <% if @protocol.science_direct %>
                  <tr>
                    <td> Science Direct Digital Library </td>
                    <td><%= @protocol.query + '&date=' + @protocol.from.to_s + '-' + @protocol.to.to_s %></td>
                  </tr>
              <% end %>
              <% if @protocol.scopus %>
                  <tr>
                    <td> Scopus Digital Library </td>
                    <td><%= @protocol.query + '&date=' + @protocol.from.to_s + '-' + @protocol.to.to_s %></td>
                  </tr>
              <% end %>
              <% if @protocol.acm %>
                  <tr>
                    <td> ACM Digital Library </td>
                    <td><%= @protocol.query + '&dte=' + @protocol.from.to_s + '&bfr=' + @protocol.to.to_s %></td>
                  </tr>
              <% end %>
              <% if @protocol.springer %>
                  <tr>
                    <td> Springer Link Digital Library </td>
                    <td><%= @protocol.query + '&facet-start-year=' + @protocol.from.to_s + '&facet-end-year=' + @protocol.to.to_s %></td>
                  </tr>
              <% end %>
              </table>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/protocols/selected.html.erb
<br>

<ol class="breadcrumb">
  <li><%= link_to 'Protocolo', protocol_path %></li>
  <li><%= link_to 'Execução da Busca', search_protocol_path %></li>
  <li><%= link_to 'Resultados Retornados', reference_path %></li>
  <li class="active"> Trabalhos pré-selecionados </li>
  <li><%= link_to 'Trabalhos selecionados', included_users_protocol_path %></li>
</ol>

<% if @empty_ieee && @empty_scidir && @empty_acm && @empty_springer %>
    <div class="alert alert-info"><b> Nenhum trabalho pré-selecionado na revisão </b></div>
<% end %>

<% unless @empty_ieee %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <b><%= link_to 'IEEE Xplore Digital Library', ieee_path %> </b>
      </div>
      <div class="panel-body">
        <div class="container-fluid">
          <table class="table table-hover">
            <thead>
            <tr>
              <th>Título</th>
              <th>Autores</th>
              <th>Seleção</th>
              <th></th>
            </tr>
            </thead>
            <tbody>
            <% @selected_ieee.each do |ref| %>
                <tr>
                  <td><%= link_to ref.title, ref.link %></td>
                  <td><%= ref.author %></td>
                  <td style="width: 130px">
                    <%= link_to include_ieees_users_protocol_path(ref), method: :put, class: 'btn btn-default btn-sm', title: 'Incluir' do %>
                        <span class="glyphicon glyphicon-ok" ></span>
                    <% end %>
                    <%= link_to exclude_ieees_users_protocol_path(ref), method: :put, class: 'btn btn-default btn-sm', title: 'Excluir' do %>
                        <span class="glyphicon glyphicon-remove"></span>
                    <% end %>
                    <%= link_to maybe_ieees_users_protocol_path(ref), method: :put, class: 'btn btn-default btn-sm', title: 'Talvez' do %>
                        <span class="glyphicon glyphicon-question-sign"></span>
                    <% end %>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
<% end %>

<% unless @empty_scidir %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <b><%= link_to 'Science Direct Digital Library', scidir_path %></b>
      </div>
      <div class="panel-body">
        <div class="container-fluid">
            <table class="table table-hover">
              <thead>
              <tr>
                <th>Título</th>
                <th>Autores</th>
                <th>Seleção</th>
                <th></th>
              </tr>
              </thead>
              <tbody>
              <% @selected_scidir.each do |ref| %>
                  <tr>
                    <td><%= link_to ref.title, ref.link %></td>
                    <td><%= ref.author %></td>
                    <td style="width: 130px">
                      <%= link_to include_scidirs_users_protocol_path(ref), method: :put, class: 'btn btn-default btn-sm', title: 'Incluir' do %>
                          <span class="glyphicon glyphicon-ok" ></span>
                      <% end %>
                      <%= link_to exclude_scidirs_users_protocol_path(ref), method: :put, class: 'btn btn-default btn-sm', title: 'Excluir' do %>
                          <span class="glyphicon glyphicon-remove"></span>
                      <% end %>
                      <%= link_to maybe_scidirs_users_protocol_path(ref), method: :put, class: 'btn btn-default btn-sm', title: 'Talvez' do %>
                          <span class="glyphicon glyphicon-question-sign"></span>
                      <% end %>
                    </td>
                  </tr>
              <% end %>
              </tbody>
            </table>
        </div>
      </div>
    </div>
<% end %>

<% unless @empty_acm %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <b><%= link_to 'ACM Digital Library', acm_path %></b>
      </div>
      <div class="panel-body">
        <div class="container-fluid">
          <table class="table table-hover">
            <thead>
            <tr>
              <th>Título</th>
              <th>Autores</th>
              <th>Seleção</th>
              <th></th>
            </tr>
            </thead>
            <tbody>
            <% @selected_acm.each do |ref| %>
                <tr>
                  <td><%= link_to ref.title, ref.link %></td>
                  <td><%= ref.author %></td>
                  <td style="width: 130px">
                    <%= link_to include_acms_users_protocol_path(ref), method: :put, class: 'btn btn-default btn-sm', title: 'Incluir' do %>
                        <span class="glyphicon glyphicon-ok" ></span>
                    <% end %>
                    <%= link_to exclude_acms_users_protocol_path(ref), method: :put, class: 'btn btn-default btn-sm', title: 'Excluir' do %>
                        <span class="glyphicon glyphicon-remove"></span>
                    <% end %>
                    <%= link_to maybe_acms_users_protocol_path(ref), method: :put, class: 'btn btn-default btn-sm', title: 'Talvez' do %>
                        <span class="glyphicon glyphicon-question-sign"></span>
                    <% end %>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
<% end %>

<% unless @empty_springer %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <b><%= link_to 'Springer Link Digital Library', springer_path %></b>
      </div>
      <div class="panel-body">
        <div class="container-fluid">
          <table class="table table-hover">
            <thead>
            <tr>
              <th>Título</th>
              <th>Autores</th>
              <th>Seleção</th>
              <th></th>
            </tr>
            </thead>
            <tbody>
            <% @selected_springer.each do |ref| %>
                <tr>
                  <td><%= link_to ref.title, ref.link %></td>
                  <td><%= ref.author %></td>
                  <td style="width: 130px">
                    <%= link_to include_springers_users_protocol_path(ref), method: :put, class: 'btn btn-default btn-sm', title: 'Incluir' do %>
                        <span class="glyphicon glyphicon-ok" ></span>
                    <% end %>
                    <%= link_to exclude_springers_users_protocol_path(ref), method: :put, class: 'btn btn-default btn-sm', title: 'Excluir' do %>
                        <span class="glyphicon glyphicon-remove"></span>
                    <% end %>
                    <%= link_to maybe_springers_users_protocol_path(ref), method: :put, class: 'btn btn-default btn-sm', title: 'Talvez' do %>
                        <span class="glyphicon glyphicon-question-sign"></span>
                    <% end %>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
<% end %>